/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 bot.glb -kKmsrT
Author: Vetech82 (https://sketchfab.com/Vetech82)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/quadrocopter-drone-animated-0ad12799f89b45968afd9dcf9bee9467
Title: Quadrocopter Drone - animated
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/glb/bot-transformed.glb");
  const { actions, names } = useAnimations(animations, group);
  useEffect(() => {
    actions[names[0]].fadeIn(0).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={2.5} name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01} userData={{ name: "RootNode" }}>
          <group
            name="Empty"
            position={[0.092, 70.439, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={34.142}
            userData={{ name: "Empty" }}
          />
          <group
            name="Empty006"
            position={[-79.161, 65.036, -77.296]}
            scale={100}
            userData={{ name: "Empty.006" }}
          />
          <group
            name="Empty007"
            position={[79.345, 65.036, -77.296]}
            scale={100}
            userData={{ name: "Empty.007" }}
          />
          <group
            name="Empty008"
            position={[79.345, 65.036, 77.296]}
            scale={100}
            userData={{ name: "Empty.008" }}
          />
          <group
            name="Empty009"
            position={[-79.161, 65.036, 77.296]}
            scale={100}
            userData={{ name: "Empty.009" }}
          />
          <group
            name="Cube013"
            position={[0.092, 67.932, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cube.013" }}
          >
            <mesh
              name="Cube013_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube013_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.013_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube014"
            position={[0.012, 62.87, 34.059]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Cube.014" }}
          >
            <mesh
              name="Cube014_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube014_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.014_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane007"
            position={[-32.783, 64.231, 33.066]}
            rotation={[-0.832, -0.569, -0.534]}
            scale={100}
            userData={{ name: "Plane.007" }}
          >
            <mesh
              name="Plane007_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane007_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.007_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere007"
            position={[0.092, 71.768, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Sphere.007" }}
          >
            <mesh
              name="Sphere007_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere007_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.007_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder019"
            position={[41.51, 64.913, 17.04]}
            rotation={[-Math.PI / 2, 0.827, 0]}
            scale={100}
            userData={{ name: "Cylinder.019" }}
          >
            <mesh
              name="Cylinder019_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder019_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.019_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder022"
            position={[-16.438, 65.914, 41.231]}
            rotation={[-0.808, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.022" }}
          >
            <mesh
              name="Cylinder022_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder022_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.022_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube025"
            position={[34.151, 62.87, 0.08]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
            userData={{ name: "Cube.025" }}
          >
            <mesh
              name="Cube025_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube025_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.025_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube012"
            position={[0.012, 62.87, -34.059]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Cube.012" }}
          >
            <mesh
              name="Cube012_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube012_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.012_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane018"
            position={[32.967, 64.231, 33.066]}
            rotation={[-0.832, -0.569, -0.534]}
            scale={100}
            userData={{ name: "Plane.018" }}
          >
            <mesh
              name="Plane018_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane018_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.018_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane019"
            position={[-32.783, 64.231, -33.066]}
            rotation={[-0.832, -0.569, -0.534]}
            scale={100}
            userData={{ name: "Plane.019" }}
          >
            <mesh
              name="Plane019_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane019_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.019_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder050"
            position={[41.51, 64.913, -16.879]}
            rotation={[-Math.PI / 2, 0.827, 0]}
            scale={100}
            userData={{ name: "Cylinder.050" }}
          >
            <mesh
              name="Cylinder050_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder050_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.050_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder051"
            position={[-41.325, 64.913, 17.04]}
            rotation={[-Math.PI / 2, 0.827, 0]}
            scale={100}
            userData={{ name: "Cylinder.051" }}
          >
            <mesh
              name="Cylinder051_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder051_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.051_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder052"
            position={[-41.325, 64.913, -16.879]}
            rotation={[-Math.PI / 2, 0.827, 0]}
            scale={100}
            userData={{ name: "Cylinder.052" }}
          >
            <mesh
              name="Cylinder052_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder052_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.052_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder059"
            position={[16.462, 65.914, 41.231]}
            rotation={[-0.808, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.059" }}
          >
            <mesh
              name="Cylinder059_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder059_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.059_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder060"
            position={[-16.438, 65.914, -41.231]}
            rotation={[-0.808, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.060" }}
          >
            <mesh
              name="Cylinder060_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder060_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.060_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder061"
            position={[16.462, 65.914, -41.231]}
            rotation={[-0.808, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.061" }}
          >
            <mesh
              name="Cylinder061_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder061_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.061_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere059"
            position={[32.529, 68.424, 31.699]}
            rotation={[-0.838, 0.631, 0.58]}
            scale={100}
            userData={{ name: "Sphere.059" }}
          >
            <mesh
              name="Sphere059_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere059_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.059_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere060"
            position={[-31.462, 68.424, 32.577]}
            rotation={[-0.792, -0.568, -0.499]}
            scale={100}
            userData={{ name: "Sphere.060" }}
          >
            <mesh
              name="Sphere060_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere060_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.060_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere061"
            position={[-32.437, 68.424, -31.604]}
            rotation={[-2.302, -0.633, -2.559]}
            scale={100}
            userData={{ name: "Sphere.061" }}
          >
            <mesh
              name="Sphere061_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere061_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.061_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder117"
            position={[0, 54.056, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.117" }}
          >
            <mesh
              name="Cylinder117_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder117_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.117_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder118"
            position={[0, 54.056, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.118" }}
          >
            <mesh
              name="Cylinder118_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder118_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.118_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder119"
            position={[0.093, 54.056, -0.092]}
            rotation={[-Math.PI / 2, 0, -1.574]}
            scale={100}
            userData={{ name: "Cylinder.119" }}
          >
            <mesh
              name="Cylinder119_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder119_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.119_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder120"
            position={[0.093, 54.056, -0.092]}
            rotation={[-Math.PI / 2, 0, -1.574]}
            scale={100}
            userData={{ name: "Cylinder.120" }}
          >
            <mesh
              name="Cylinder120_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder120_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.120_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube016"
            position={[0.092, 51.685, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cube.016" }}
          >
            <mesh
              name="Cube016_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube016_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.016_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane013"
            position={[-23.619, 51.476, 23.41]}
            rotation={[-0.832, -0.569, -0.534]}
            scale={100}
            userData={{ name: "Plane.013" }}
          >
            <mesh
              name="Plane013_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane013_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.013_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane020"
            position={[32.967, 64.231, -33.066]}
            rotation={[-0.832, -0.569, -0.534]}
            scale={100}
            userData={{ name: "Plane.020" }}
          >
            <mesh
              name="Plane020_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane020_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.020_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane036"
            position={[23.803, 51.476, 23.41]}
            rotation={[-0.832, -0.569, -0.534]}
            scale={100}
            userData={{ name: "Plane.036" }}
          >
            <mesh
              name="Plane036_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane036_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.036_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane037"
            position={[-23.619, 51.476, -23.41]}
            rotation={[-0.832, -0.569, -0.534]}
            scale={100}
            userData={{ name: "Plane.037" }}
          >
            <mesh
              name="Plane037_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane037_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.037_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube029"
            position={[-33.967, 62.87, 0.08]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={100}
            userData={{ name: "Cube.029" }}
          >
            <mesh
              name="Cube029_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube029_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.029_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere062"
            position={[31.618, 68.424, -32.606]}
            rotation={[-2.35, 0.567, 2.643]}
            scale={100}
            userData={{ name: "Sphere.062" }}
          >
            <mesh
              name="Sphere062_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere062_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.062_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube020"
            position={[0.092, 46.801, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cube.020" }}
          >
            <mesh
              name="Cube020_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube020_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.020_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube021"
            position={[11.653, 46.144, 11.266]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cube.021" }}
          >
            <mesh
              name="Cube021_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube021_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.021_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane038"
            position={[23.803, 51.476, -23.41]}
            rotation={[-0.832, -0.569, -0.534]}
            scale={100}
            userData={{ name: "Plane.038" }}
          >
            <mesh
              name="Plane038_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane038_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.038_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube026"
            position={[-11.469, 46.144, 11.266]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cube.026" }}
          >
            <mesh
              name="Cube026_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube026_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.026_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube028"
            position={[-11.469, 46.144, -11.266]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cube.028" }}
          >
            <mesh
              name="Cube028_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube028_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.028_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere009"
            position={[0.092, 44.126, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Sphere.009" }}
          >
            <mesh
              name="Sphere009_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere009_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.009_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube027"
            position={[11.653, 46.144, -11.266]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cube.027" }}
          >
            <mesh
              name="Cube027_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube027_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.027_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube015"
            position={[0.092, 49.549, 42.334]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cube.015" }}
          >
            <mesh
              name="Cube015_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube015_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.015_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder013"
            position={[14.506, 39.589, 43.448]}
            rotation={[-1.666, -1.072, -0.102]}
            scale={100}
            userData={{ name: "Cylinder.013" }}
          >
            <mesh
              name="Cylinder013_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder013_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.013_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder014"
            position={[26.104, 33.305, 44.051]}
            rotation={[-1.666, -1.072, -0.102]}
            scale={100}
            userData={{ name: "Cylinder.014" }}
          >
            <mesh
              name="Cylinder014_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder014_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.014_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube017"
            position={[42.427, 49.631, 0]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Cube.017" }}
          >
            <mesh
              name="Cube017_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube017_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.017_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder020"
            position={[43.541, 39.589, -14.414]}
            rotation={[-0.497, -0.046, 1.553]}
            scale={100}
            userData={{ name: "Cylinder.020" }}
          >
            <mesh
              name="Cylinder020_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder020_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.020_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder021"
            position={[44.143, 33.305, -26.012]}
            rotation={[-0.497, -0.046, 1.553]}
            scale={100}
            userData={{ name: "Cylinder.021" }}
          >
            <mesh
              name="Cylinder021_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder021_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.021_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube018"
            position={[0.092, 49.549, -42.334]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cube.018" }}
          >
            <mesh
              name="Cube018_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube018_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.018_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder028"
            position={[-14.321, 39.589, 43.448]}
            rotation={[-1.666, -1.072, -0.102]}
            scale={100}
            userData={{ name: "Cylinder.028" }}
          >
            <mesh
              name="Cylinder028_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder028_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.028_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder029"
            position={[14.506, 39.589, -43.448]}
            rotation={[-1.666, -1.072, -0.102]}
            scale={100}
            userData={{ name: "Cylinder.029" }}
          >
            <mesh
              name="Cylinder029_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder029_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.029_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder030"
            position={[-14.321, 39.589, -43.448]}
            rotation={[-1.666, -1.072, -0.102]}
            scale={100}
            userData={{ name: "Cylinder.030" }}
          >
            <mesh
              name="Cylinder030_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder030_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.030_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder031"
            position={[-25.92, 33.305, 44.051]}
            rotation={[-1.666, -1.072, -0.102]}
            scale={100}
            userData={{ name: "Cylinder.031" }}
          >
            <mesh
              name="Cylinder031_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder031_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.031_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder032"
            position={[26.104, 33.305, -44.051]}
            rotation={[-1.666, -1.072, -0.102]}
            scale={100}
            userData={{ name: "Cylinder.032" }}
          >
            <mesh
              name="Cylinder032_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder032_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.032_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder033"
            position={[-25.92, 33.305, -44.051]}
            rotation={[-1.666, -1.072, -0.102]}
            scale={100}
            userData={{ name: "Cylinder.033" }}
          >
            <mesh
              name="Cylinder033_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder033_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.033_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cube019"
            position={[-42.242, 49.631, 0]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Cube.019" }}
          >
            <mesh
              name="Cube019_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube019_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cube.019_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder053"
            position={[-43.356, 39.589, -14.414]}
            rotation={[-0.497, -0.046, 1.553]}
            scale={100}
            userData={{ name: "Cylinder.053" }}
          >
            <mesh
              name="Cylinder053_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder053_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.053_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder054"
            position={[43.541, 39.589, 14.414]}
            rotation={[-0.497, -0.046, 1.553]}
            scale={100}
            userData={{ name: "Cylinder.054" }}
          >
            <mesh
              name="Cylinder054_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder054_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.054_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder055"
            position={[-43.356, 39.589, 14.414]}
            rotation={[-0.497, -0.046, 1.553]}
            scale={100}
            userData={{ name: "Cylinder.055" }}
          >
            <mesh
              name="Cylinder055_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder055_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.055_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder056"
            position={[-43.959, 33.305, -26.012]}
            rotation={[-0.497, -0.046, 1.553]}
            scale={100}
            userData={{ name: "Cylinder.056" }}
          >
            <mesh
              name="Cylinder056_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder056_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.056_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder057"
            position={[44.143, 33.305, 26.012]}
            rotation={[-0.497, -0.046, 1.553]}
            scale={100}
            userData={{ name: "Cylinder.057" }}
          >
            <mesh
              name="Cylinder057_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder057_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.057_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder058"
            position={[-43.959, 33.305, 26.012]}
            rotation={[-0.497, -0.046, 1.553]}
            scale={100}
            userData={{ name: "Cylinder.058" }}
          >
            <mesh
              name="Cylinder058_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder058_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.058_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere008"
            position={[43.309, 31.043, -32.025]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Sphere.008" }}
          >
            <mesh
              name="Sphere008_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere008_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.008_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere013"
            position={[43.861, 31.44, -29.375]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Sphere.013" }}
          >
            <mesh
              name="Sphere013_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere013_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.013_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere015"
            position={[-43.676, 31.44, -29.375]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Sphere.015" }}
          >
            <mesh
              name="Sphere015_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere015_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.015_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane022"
            position={[37.722, 30.005, -37.6]}
            rotation={[0, -0.741, 0]}
            scale={100}
            userData={{ name: "Plane.022" }}
          >
            <mesh
              name="Plane022_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane022_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.022_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane023"
            position={[-37.538, 30.005, -37.6]}
            rotation={[0, -0.741, 0]}
            scale={100}
            userData={{ name: "Plane.023" }}
          >
            <mesh
              name="Plane023_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane023_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.023_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder026"
            position={[43.907, 28.125, -43.501]}
            rotation={[-Math.PI, 0.742, Math.PI / 2]}
            scale={100}
            userData={{ name: "Cylinder.026" }}
          >
            <mesh
              name="Cylinder026_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder026_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.026_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder027"
            position={[-43.723, 28.125, -43.501]}
            rotation={[-Math.PI, 0.742, Math.PI / 2]}
            scale={100}
            userData={{ name: "Cylinder.027" }}
          >
            <mesh
              name="Cylinder027_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder027_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.027_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere018"
            position={[32.117, 31.043, -43.217]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Sphere.018" }}
          >
            <mesh
              name="Sphere018_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere018_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.018_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere019"
            position={[-31.933, 31.043, -43.217]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Sphere.019" }}
          >
            <mesh
              name="Sphere019_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere019_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.019_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane025"
            position={[52, 24.713, -54.623]}
            rotation={[0, -0.741, -0.05]}
            scale={100}
            userData={{ name: "Plane.025" }}
          >
            <mesh
              name="Plane025_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane025_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.025_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane026"
            position={[-51.816, 24.713, -54.623]}
            rotation={[0, -0.741, -0.05]}
            scale={100}
            userData={{ name: "Plane.026" }}
          >
            <mesh
              name="Plane026_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane026_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.026_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere020"
            position={[-43.124, 31.043, -32.025]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Sphere.020" }}
          >
            <mesh
              name="Sphere020_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere020_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.020_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere031"
            position={[29.467, 31.44, -43.769]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Sphere.031" }}
          >
            <mesh
              name="Sphere031_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere031_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.031_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere032"
            position={[-29.282, 31.44, -43.769]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Sphere.032" }}
          >
            <mesh
              name="Sphere032_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere032_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.032_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere016"
            position={[-43.676, 31.44, 29.375]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Sphere.016" }}
          >
            <mesh
              name="Sphere016_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere016_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.016_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane021"
            position={[-37.538, 30.005, 37.6]}
            rotation={[0, -0.741, 0]}
            scale={100}
            userData={{ name: "Plane.021" }}
          >
            <mesh
              name="Plane021_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane021_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.021_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder025"
            position={[-43.723, 28.125, 43.501]}
            rotation={[-Math.PI, 0.742, Math.PI / 2]}
            scale={100}
            userData={{ name: "Cylinder.025" }}
          >
            <mesh
              name="Cylinder025_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder025_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.025_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane024"
            position={[-51.816, 24.713, 54.623]}
            rotation={[0, -0.741, -0.05]}
            scale={100}
            userData={{ name: "Plane.024" }}
          >
            <mesh
              name="Plane024_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane024_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.024_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere022"
            position={[-43.124, 31.043, 32.025]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Sphere.022" }}
          >
            <mesh
              name="Sphere022_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere022_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.022_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere017"
            position={[-31.933, 31.043, 43.217]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Sphere.017" }}
          >
            <mesh
              name="Sphere017_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere017_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.017_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere030"
            position={[-29.282, 31.44, 43.769]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Sphere.030" }}
          >
            <mesh
              name="Sphere030_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere030_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.030_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane008"
            position={[37.722, 30.005, 37.6]}
            rotation={[0, -0.741, 0]}
            scale={100}
            userData={{ name: "Plane.008" }}
          >
            <mesh
              name="Plane008_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane008_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.008_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Cylinder012"
            position={[43.907, 28.125, 43.501]}
            rotation={[-Math.PI, 0.742, Math.PI / 2]}
            scale={100}
            userData={{ name: "Cylinder.012" }}
          >
            <mesh
              name="Cylinder012_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={
                nodes.Cylinder012_TT_checker_4096x4096_UV_GRID_0.geometry
              }
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Cylinder.012_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere006"
            position={[32.117, 31.043, 43.217]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Sphere.006" }}
          >
            <mesh
              name="Sphere006_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere006_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.006_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Plane009"
            position={[52, 24.713, 54.623]}
            rotation={[0, -0.741, -0.05]}
            scale={100}
            userData={{ name: "Plane.009" }}
          >
            <mesh
              name="Plane009_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane009_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Plane.009_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere011"
            position={[29.467, 31.44, 43.769]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Sphere.011" }}
          >
            <mesh
              name="Sphere011_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere011_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.011_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere014"
            position={[43.861, 31.44, 29.375]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Sphere.014" }}
          >
            <mesh
              name="Sphere014_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere014_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.014_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Sphere021"
            position={[43.309, 31.043, 32.025]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
            userData={{ name: "Sphere.021" }}
          >
            <mesh
              name="Sphere021_TT_checker_4096x4096_UV_GRID_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere021_TT_checker_4096x4096_UV_GRID_0.geometry}
              material={materials.TT_checker_4096x4096_UV_GRID}
              userData={{ name: "Sphere.021_TT_checker_4096x4096_UV_GRID_0" }}
            />
          </group>
          <group
            name="Torus002"
            position={[84.219, 52.64, 82.325]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.002" }}
          >
            <mesh
              name="Torus002_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus002_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.002_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder015"
            position={[79.338, 19.798, 77.304]}
            rotation={[0, -0.741, 0]}
            scale={100}
            userData={{ name: "Cylinder.015" }}
          >
            <mesh
              name="Cylinder015_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder015_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.015_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder016"
            position={[79.345, 35.227, 77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.016" }}
          >
            <mesh
              name="Cylinder016_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder016_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.016_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder017"
            position={[79.345, 51.185, 77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.017" }}
          >
            <mesh
              name="Cylinder017_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder017_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.017_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder018"
            position={[79.345, 65.036, 77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.018" }}
          >
            <mesh
              name="Cylinder018_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder018_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.018_mat_01_0" }}
            />
          </group>
          <group
            name="Plane010"
            position={[99.266, 59.74, 75.923]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Plane.010" }}
          >
            <mesh
              name="Plane010_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane010_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.010_mat_01_0" }}
            />
          </group>
          <group
            name="Plane011"
            position={[68.196, 59.74, 60.731]}
            rotation={[-Math.PI / 2, 0, 2.094]}
            scale={100}
            userData={{ name: "Plane.011" }}
          >
            <mesh
              name="Plane011_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane011_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.011_mat_01_0" }}
            />
          </group>
          <group
            name="Plane012"
            position={[70.574, 59.74, 95.234]}
            rotation={[-Math.PI / 2, 0, -2.094]}
            scale={100}
            userData={{ name: "Plane.012" }}
          >
            <mesh
              name="Plane012_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane012_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.012_mat_01_0" }}
            />
          </group>
          <group
            name="Torus003"
            position={[83.406, 62.968, 81.599]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.003" }}
          >
            <mesh
              name="Torus003_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus003_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.003_mat_01_0" }}
            />
          </group>
          <group
            name="Sphere010"
            position={[69.405, 19.759, 88.359]}
            rotation={[0, -0.743, Math.PI]}
            scale={100}
            userData={{ name: "Sphere.010" }}
          >
            <mesh
              name="Sphere010_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere010_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Sphere.010_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder023"
            position={[79.345, 57.075, 77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.023" }}
          >
            <mesh
              name="Cylinder023_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder023_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.023_mat_01_0" }}
            />
          </group>
          <group
            name="Torus005"
            position={[-84.034, 52.64, 82.325]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.005" }}
          >
            <mesh
              name="Torus005_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus005_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.005_mat_01_0" }}
            />
          </group>
          <group
            name="Torus006"
            position={[84.219, 52.64, -82.325]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.006" }}
          >
            <mesh
              name="Torus006_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus006_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.006_mat_01_0" }}
            />
          </group>
          <group
            name="Torus007"
            position={[-84.034, 52.64, -82.325]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.007" }}
          >
            <mesh
              name="Torus007_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus007_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.007_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder034"
            position={[-79.153, 19.798, 77.304]}
            rotation={[0, -0.741, 0]}
            scale={100}
            userData={{ name: "Cylinder.034" }}
          >
            <mesh
              name="Cylinder034_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder034_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.034_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder035"
            position={[79.338, 19.798, -77.304]}
            rotation={[0, -0.741, 0]}
            scale={100}
            userData={{ name: "Cylinder.035" }}
          >
            <mesh
              name="Cylinder035_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder035_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.035_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder036"
            position={[-79.154, 19.798, -77.304]}
            rotation={[0, -0.741, 0]}
            scale={100}
            userData={{ name: "Cylinder.036" }}
          >
            <mesh
              name="Cylinder036_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder036_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.036_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder037"
            position={[-79.161, 35.227, 77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.037" }}
          >
            <mesh
              name="Cylinder037_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder037_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.037_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder038"
            position={[79.345, 35.227, -77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.038" }}
          >
            <mesh
              name="Cylinder038_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder038_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.038_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder039"
            position={[-79.161, 35.227, -77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.039" }}
          >
            <mesh
              name="Cylinder039_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder039_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.039_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder040"
            position={[-79.161, 51.185, 77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.040" }}
          >
            <mesh
              name="Cylinder040_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder040_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.040_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder041"
            position={[79.345, 51.185, -77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.041" }}
          >
            <mesh
              name="Cylinder041_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder041_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.041_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder042"
            position={[-79.161, 51.185, -77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.042" }}
          >
            <mesh
              name="Cylinder042_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder042_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.042_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder044"
            position={[-79.161, 65.036, 77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.044" }}
          >
            <mesh
              name="Cylinder044_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder044_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.044_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder046"
            position={[79.345, 65.036, -77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.046" }}
          >
            <mesh
              name="Cylinder046_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder046_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.046_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder048"
            position={[-79.161, 65.036, -77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.048" }}
          >
            <mesh
              name="Cylinder048_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder048_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.048_mat_01_0" }}
            />
          </group>
          <group
            name="Plane027"
            position={[-99.081, 59.74, 75.923]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Plane.027" }}
          >
            <mesh
              name="Plane027_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane027_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.027_mat_01_0" }}
            />
          </group>
          <group
            name="Plane028"
            position={[99.266, 59.74, -75.923]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Plane.028" }}
          >
            <mesh
              name="Plane028_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane028_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.028_mat_01_0" }}
            />
          </group>
          <group
            name="Plane029"
            position={[-99.081, 59.74, -75.923]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Plane.029" }}
          >
            <mesh
              name="Plane029_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane029_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.029_mat_01_0" }}
            />
          </group>
          <group
            name="Plane030"
            position={[-68.011, 59.74, 60.731]}
            rotation={[-Math.PI / 2, 0, 2.094]}
            scale={100}
            userData={{ name: "Plane.030" }}
          >
            <mesh
              name="Plane030_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane030_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.030_mat_01_0" }}
            />
          </group>
          <group
            name="Plane031"
            position={[68.196, 59.74, -60.731]}
            rotation={[-Math.PI / 2, 0, 2.094]}
            scale={100}
            userData={{ name: "Plane.031" }}
          >
            <mesh
              name="Plane031_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane031_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.031_mat_01_0" }}
            />
          </group>
          <group
            name="Plane032"
            position={[-68.011, 59.74, -60.731]}
            rotation={[-Math.PI / 2, 0, 2.094]}
            scale={100}
            userData={{ name: "Plane.032" }}
          >
            <mesh
              name="Plane032_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane032_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.032_mat_01_0" }}
            />
          </group>
          <group
            name="Plane033"
            position={[-70.39, 59.74, 95.234]}
            rotation={[-Math.PI / 2, 0, -2.094]}
            scale={100}
            userData={{ name: "Plane.033" }}
          >
            <mesh
              name="Plane033_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane033_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.033_mat_01_0" }}
            />
          </group>
          <group
            name="Plane034"
            position={[70.574, 59.74, -95.234]}
            rotation={[-Math.PI / 2, 0, -2.094]}
            scale={100}
            userData={{ name: "Plane.034" }}
          >
            <mesh
              name="Plane034_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane034_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.034_mat_01_0" }}
            />
          </group>
          <group
            name="Plane035"
            position={[-70.39, 59.74, -95.234]}
            rotation={[-Math.PI / 2, 0, -2.094]}
            scale={100}
            userData={{ name: "Plane.035" }}
          >
            <mesh
              name="Plane035_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Plane035_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Plane.035_mat_01_0" }}
            />
          </group>
          <group
            name="Torus008"
            position={[-83.221, 62.968, 81.599]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.008" }}
          >
            <mesh
              name="Torus008_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus008_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.008_mat_01_0" }}
            />
          </group>
          <group
            name="Torus009"
            position={[83.406, 62.968, -81.599]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.009" }}
          >
            <mesh
              name="Torus009_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus009_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.009_mat_01_0" }}
            />
          </group>
          <group
            name="Torus010"
            position={[-83.221, 62.968, -81.599]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.010" }}
          >
            <mesh
              name="Torus010_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus010_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.010_mat_01_0" }}
            />
          </group>
          <group
            name="Sphere023"
            position={[89.49, 19.759, 66.421]}
            rotation={[0, -0.743, Math.PI]}
            scale={100}
            userData={{ name: "Sphere.023" }}
          >
            <mesh
              name="Sphere023_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere023_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Sphere.023_mat_01_0" }}
            />
          </group>
          <group
            name="Sphere024"
            position={[-69.221, 19.759, 88.359]}
            rotation={[0, -0.743, Math.PI]}
            scale={100}
            userData={{ name: "Sphere.024" }}
          >
            <mesh
              name="Sphere024_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere024_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Sphere.024_mat_01_0" }}
            />
          </group>
          <group
            name="Sphere025"
            position={[-89.305, 19.759, 66.421]}
            rotation={[0, -0.743, Math.PI]}
            scale={100}
            userData={{ name: "Sphere.025" }}
          >
            <mesh
              name="Sphere025_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere025_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Sphere.025_mat_01_0" }}
            />
          </group>
          <group
            name="Sphere026"
            position={[69.405, 19.759, -88.359]}
            rotation={[0, -0.743, Math.PI]}
            scale={100}
            userData={{ name: "Sphere.026" }}
          >
            <mesh
              name="Sphere026_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere026_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Sphere.026_mat_01_0" }}
            />
          </group>
          <group
            name="Sphere027"
            position={[89.49, 19.759, -66.421]}
            rotation={[0, -0.743, Math.PI]}
            scale={100}
            userData={{ name: "Sphere.027" }}
          >
            <mesh
              name="Sphere027_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere027_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Sphere.027_mat_01_0" }}
            />
          </group>
          <group
            name="Sphere028"
            position={[-69.221, 19.759, -88.359]}
            rotation={[0, -0.743, Math.PI]}
            scale={100}
            userData={{ name: "Sphere.028" }}
          >
            <mesh
              name="Sphere028_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere028_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Sphere.028_mat_01_0" }}
            />
          </group>
          <group
            name="Sphere029"
            position={[-89.305, 19.759, -66.421]}
            rotation={[0, -0.743, Math.PI]}
            scale={100}
            userData={{ name: "Sphere.029" }}
          >
            <mesh
              name="Sphere029_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Sphere029_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Sphere.029_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder062"
            position={[-79.161, 57.075, 77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.062" }}
          >
            <mesh
              name="Cylinder062_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder062_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.062_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder063"
            position={[79.345, 57.075, -77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.063" }}
          >
            <mesh
              name="Cylinder063_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder063_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.063_mat_01_0" }}
            />
          </group>
          <group
            name="Cylinder064"
            position={[-79.161, 57.075, -77.296]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Cylinder.064" }}
          >
            <mesh
              name="Cylinder064_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder064_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cylinder.064_mat_01_0" }}
            />
          </group>
          <group
            name="Cube023"
            position={[78.723, 49.84, 55.671]}
            rotation={[-Math.PI / 2, 0, 0.053]}
            scale={100}
            userData={{ name: "Cube.023" }}
          >
            <mesh
              name="Cube023_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube023_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cube.023_mat_01_0" }}
            />
          </group>
          <group
            name="Cube031"
            position={[78.723, 49.84, 55.671]}
            rotation={[-Math.PI / 2, 0, 0.053]}
            scale={100}
            userData={{ name: "Cube.031" }}
          >
            <mesh
              name="Cube031_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube031_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cube.031_mat_01_0" }}
            />
          </group>
          <group
            name="Cube034"
            position={[78.723, 49.84, 55.671]}
            rotation={[-Math.PI / 2, 0, 0.053]}
            scale={100}
            userData={{ name: "Cube.034" }}
          >
            <mesh
              name="Cube034_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube034_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cube.034_mat_01_0" }}
            />
          </group>
          <group
            name="Cube036"
            position={[78.723, 49.84, 55.671]}
            rotation={[-Math.PI / 2, 0, 0.053]}
            scale={100}
            userData={{ name: "Cube.036" }}
          >
            <mesh
              name="Cube036_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Cube036_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Cube.036_mat_01_0" }}
            />
          </group>
          <group
            name="Torus019"
            position={[83.406, 55.191, -81.599]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.019" }}
          >
            <mesh
              name="Torus019_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus019_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.019_mat_01_0" }}
            />
          </group>
          <group
            name="Torus020"
            position={[83.406, 54.734, 81.599]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.020" }}
          >
            <mesh
              name="Torus020_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus020_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.020_mat_01_0" }}
            />
          </group>
          <group
            name="Torus021"
            position={[-83.221, 54.734, 81.599]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.021" }}
          >
            <mesh
              name="Torus021_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus021_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.021_mat_01_0" }}
            />
          </group>
          <group
            name="Torus022"
            position={[-83.221, 54.734, -81.599]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
            userData={{ name: "Torus.022" }}
          >
            <mesh
              name="Torus022_mat_01_0"
              castShadow
              receiveShadow
              geometry={nodes.Torus022_mat_01_0.geometry}
              material={materials.mat_01}
              userData={{ name: "Torus.022_mat_01_0" }}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/glb/bot-transformed.glb");
