/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 tokyo.glb -T
Author: William Domeyer (https://sketchfab.com/WilliamDomeyer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vaporwave-tokyo-sketchfab-3d-editor-challenge-4eba49b0f6f54ade836a565d98247723
Title: Vaporwave Tokyo: Sketchfab 3D Editor Challenge
*/

import { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials, animations } = useGLTF("/tokyo-transformed.glb");
  const { actions, names, ref } = useAnimations(animations);

  useEffect(() => {
    actions[names[0]].fadeIn(4).play();
    return () => actions[names[0]].fadeOut(0).play();
  }, [actions, names]);

  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_created_0" scale={0.019}>
          <group
            name="Object078_53"
            position={[76.075, 163.937, 118.597]}
            rotation={[-Math.PI / 3, 0, 0]}
            scale={3.099}
          >
            <group name="_54" position={[-97.409, -7.128, -96.27]}>
              <group name="Object078_Plastic_Soft_0_55">
                <mesh
                  name="Object_30"
                  geometry={nodes.Object_30.geometry}
                  material={materials.Plastic_Soft}
                />
              </group>
            </group>
          </group>
          <group
            name="body_56"
            position={[41.054, -198.364, 208.679]}
            rotation={[-Math.PI / 2, 0, 0.947]}
          >
            <group name="_57" position={[0, -0.254, 1.817]}>
              <group name="body_normal_0_58">
                <mesh
                  name="Object_34"
                  geometry={nodes.Object_34.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
            <group name="leaf_59" position={[-0.015, 1.307, 8.04]}>
              <group name="_60" position={[0.015, -1.561, -6.223]}>
                <group name="leaf_normal_0_61">
                  <mesh
                    name="Object_38"
                    geometry={nodes.Object_38.geometry}
                    material={materials.normal}
                  />
                </group>
              </group>
            </group>
            <group
              name="hand2_62"
              position={[2.127, -0.734, 5.063]}
              rotation={[0, Math.PI / 3, 0]}
            >
              <group name="_63" position={[-2.127, 0.48, -3.246]}>
                <group name="hand2_normal_0_64">
                  <mesh
                    name="Object_42"
                    geometry={nodes.Object_42.geometry}
                    material={materials.normal}
                  />
                </group>
              </group>
            </group>
            <group
              name="hand1_65"
              position={[-2.169, -0.734, 5.084]}
              rotation={[0, -Math.PI / 3, 0]}
            >
              <group name="_66" position={[2.169, 0.48, -3.267]}>
                <group name="hand1_normal_0_67">
                  <mesh
                    name="Object_46"
                    geometry={nodes.Object_46.geometry}
                    material={materials.normal}
                  />
                </group>
              </group>
            </group>
            <group name="foot2_68" position={[2.428, -0.923, 2.02]}>
              <group name="_69" position={[-2.428, 0.669, -0.203]}>
                <group name="foot2_normal_0_70">
                  <mesh
                    name="Object_50"
                    geometry={nodes.Object_50.geometry}
                    material={materials.normal}
                  />
                </group>
              </group>
            </group>
            <group name="foot1_71" position={[-2.491, -0.923, 1.978]}>
              <group name="_72" position={[2.491, 0.669, -0.161]}>
                <group name="foot1_normal_0_73">
                  <mesh
                    name="Object_54"
                    geometry={nodes.Object_54.geometry}
                    material={materials.normal}
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            name="Object608_75"
            position={[-54.38, 114.483, -87.573]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={3.099}
          >
            <group name="_76" position={[-55.32, -73.646, -80.314]}>
              <group name="Object608_metalmat_0_77">
                <mesh
                  name="Object_58"
                  geometry={nodes.Object_58.geometry}
                  material={materials.metalmat}
                />
              </group>
              <group name="Object608_paintmat_0_78">
                <mesh
                  name="Object_60"
                  geometry={nodes.Object_60.geometry}
                  material={materials.paintmat}
                />
              </group>
            </group>
          </group>
          <group
            name="wire7_91"
            position={[53.443, -91.07, 179.833]}
            rotation={[-1.534, 0, 0]}
          >
            <group name="_92" position={[-138.488, 205.266, 96.473]}>
              <group name="wire7_normal_0_93">
                <mesh
                  name="Object_87"
                  geometry={nodes.Object_87.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Object675_97"
            position={[85.462, -196.519, -246.386]}
            rotation={[-Math.PI / 2, 0, 3.113]}
          >
            <group name="_98" position={[0, 0, 76.43]}>
              <group name="Object675_metalmat_0_99">
                <mesh
                  name="Object_96"
                  geometry={nodes.Object_96.geometry}
                  material={materials.metalmat}
                />
              </group>
              <group name="Object675_paintmat_0_100">
                <mesh
                  name="Object_98"
                  geometry={nodes.Object_98.geometry}
                  material={materials.paintmat}
                />
              </group>
              <group name="Object675_glassmat_0_101">
                <mesh
                  name="Object_100"
                  geometry={nodes.Object_100.geometry}
                  material={materials.glassmat}
                />
              </group>
              <group name="Object675_outline_0_102">
                <mesh
                  name="Object_102"
                  geometry={nodes.Object_102.geometry}
                  material={materials.outline}
                />
              </group>
            </group>
            <group name="Object680_103" position={[-12.887, 0, 8.351]}>
              <group name="_104" position={[12.887, 0, 68.079]}>
                <group name="Object680_metalmat_0_105">
                  <mesh
                    name="Object_106"
                    geometry={nodes.Object_106.geometry}
                    material={materials.metalmat}
                  />
                </group>
              </group>
            </group>
            <group name="Object681_106" position={[14.29, 0, 8.351]}>
              <group name="_107" position={[12.887, 0, 68.079]}>
                <group name="Object681_metalmat_0_108">
                  <mesh
                    name="Object_110"
                    geometry={nodes.Object_110.geometry}
                    material={materials.metalmat}
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            name="Object532_109"
            position={[-29.258, -38.731, -7.815]}
            rotation={[-Math.PI / 2, 0, -0.698]}
            scale={3.099}
          >
            <group
              name="_110"
              position={[-17.707, -77.448, -30.882]}
              rotation={[0, 0, 0.698]}
            >
              <group name="Object532_normal_0_111">
                <mesh
                  name="Object_114"
                  geometry={nodes.Object_114.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Object689_115"
            position={[-245.525, -161.782, -259.308]}
            rotation={[-1.627, -0.067, -0.7]}
          >
            <group name="_116" rotation={[0, 0, 0.698]}>
              <group name="Object689_metalmat_0_117">
                <mesh
                  name="Object_122"
                  geometry={nodes.Object_122.geometry}
                  material={materials.metalmat}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane001_118"
            position={[-101.44, 184.595, -141.828]}
            rotation={[-Math.PI / 2, 0, -0.14]}
          >
            <group name="_119" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane001_normal_0_120">
                <mesh
                  name="Object_126"
                  geometry={nodes.Object_126.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane003_121"
            position={[-95.311, 184.595, -140.965]}
            rotation={[Math.PI / 2, 0, 0.14]}
            scale={-1}
          >
            <group name="_122" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane003_normal_0_123">
                <mesh
                  name="Object_130"
                  geometry={nodes.Object_130.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane104_125"
            position={[-83.171, 184.595, -140.38]}
            rotation={[-Math.PI / 2, 0, 0.3]}
          >
            <group name="_126" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane104_normal_0_127">
                <mesh
                  name="Object_134"
                  geometry={nodes.Object_134.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane103_128"
            position={[-77.258, 184.595, -142.209]}
            rotation={[Math.PI / 2, 0, -0.3]}
            scale={-1}
          >
            <group name="_129" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane103_normal_0_130">
                <mesh
                  name="Object_138"
                  geometry={nodes.Object_138.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane105_132"
            position={[133.481, 48.269, -68.276]}
            rotation={[-Math.PI / 2, 0, -1.892]}
          >
            <group name="_133" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane105_normal_0_134">
                <mesh
                  name="Object_142"
                  geometry={nodes.Object_142.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane106_136"
            position={[131.529, 48.269, -62.403]}
            rotation={[Math.PI / 2, 0, 1.892]}
            scale={-1}
          >
            <group name="_137" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane106_normal_0_138">
                <mesh
                  name="Object_146"
                  geometry={nodes.Object_146.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane108_139"
            position={[148.082, 111.708, 190.16]}
            rotation={[-Math.PI / 2, 0, 2.969]}
          >
            <group name="_140" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane108_normal_0_141">
                <mesh
                  name="Object_150"
                  geometry={nodes.Object_150.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane107_143"
            position={[141.985, 111.708, 189.096]}
            rotation={[Math.PI / 2, 0, -2.969]}
            scale={-1}
          >
            <group name="_144" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane107_normal_0_145">
                <mesh
                  name="Object_154"
                  geometry={nodes.Object_154.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane109_147"
            position={[172.103, 108.396, 188.554]}
            rotation={[-Math.PI / 2, 0, 2.068]}
          >
            <group name="_148" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane109_normal_0_149">
                <mesh
                  name="Object_158"
                  geometry={nodes.Object_158.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane110_150"
            position={[169.153, 108.396, 183.113]}
            rotation={[Math.PI / 2, 0, -2.068]}
            scale={-1}
          >
            <group name="_151" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane110_normal_0_152">
                <mesh
                  name="Object_162"
                  geometry={nodes.Object_162.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane111_153"
            position={[38.825, 198.597, 68.564]}
            rotation={[1.571, 0, -0.135]}
            scale={-1}
          >
            <group name="_154" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane111_normal_0_155">
                <mesh
                  name="Object_166"
                  geometry={nodes.Object_166.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Plane112_156"
            position={[32.692, 198.597, 69.394]}
            rotation={[-Math.PI / 2, 0, 0.135]}
          >
            <group name="_157" position={[-0.965, -3.606, -2.09]}>
              <group name="Plane112_normal_0_158">
                <mesh
                  name="Object_170"
                  geometry={nodes.Object_170.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Object704_160"
            position={[-134.881, -36.701, -123.583]}
            rotation={[-1.576, 0.01, -0.018]}
          >
            <group name="_161" position={[49.835, -98.15, 42.104]}>
              <group name="Object704_Plastic_Soft_0_162">
                <mesh
                  name="Object_174"
                  geometry={nodes.Object_174.geometry}
                  material={materials.Plastic_Soft}
                />
              </group>
              <group name="Object704_metalmat_0_163">
                <mesh
                  name="Object_176"
                  geometry={nodes.Object_176.geometry}
                  material={materials.metalmat}
                />
              </group>
            </group>
          </group>
          <group
            name="wire1_164"
            position={[11.349, -53.562, -65.672]}
            rotation={[-1.748, -0.095, 0.141]}
          >
            <group
              name="_165"
              position={[-101.137, -36.732, 53.01]}
              rotation={[0.189, 0, -0.143]}
            >
              <group name="wire1_Plastic_Soft_0_166">
                <mesh
                  name="Object_180"
                  geometry={nodes.Object_180.geometry}
                  material={materials.Plastic_Soft}
                />
              </group>
            </group>
          </group>
          <group
            name="wire2_167"
            position={[51.826, -43.974, -45.541]}
            rotation={[-1.607, -0.035, -0.803]}
          >
            <group
              name="_168"
              position={[-80.707, -112.36, 49.377]}
              rotation={[0, 0, 0.802]}
            >
              <group name="wire2_Plastic_Soft_0_169">
                <mesh
                  name="Object_184"
                  geometry={nodes.Object_184.geometry}
                  material={materials.Plastic_Soft}
                />
              </group>
            </group>
            <group
              name="Object081_170"
              position={[3.654, -65.195, -24.493]}
              rotation={[0.043, 0.012, -2.868]}
              scale={3.099}
            >
              <group
                name="_171"
                position={[-91.861, 2.868, -19.124]}
                rotation={[0, 0, -0.519]}
              >
                <group name="Object081_normal_0_172">
                  <mesh
                    name="Object_188"
                    geometry={nodes.Object_188.geometry}
                    material={materials.normal}
                  />
                </group>
              </group>
            </group>
            <group
              name="Object332_173"
              position={[3.799, -102.162, -21.43]}
              rotation={[0.051, -0.078, -2.349]}
              scale={3.099}
            >
              <group name="_174" position={[-78.668, -54.735, -19.124]}>
                <group name="Object332_normal_0_175">
                  <mesh
                    name="Object_192"
                    geometry={nodes.Object_192.geometry}
                    material={materials.normal}
                  />
                </group>
              </group>
            </group>
            <group
              name="Object682_176"
              position={[0.542, -22.699, -18.803]}
              rotation={[0.076, -0.03, -1.641]}
              scale={3.099}
            >
              <group name="_177" position={[-78.668, -54.735, -19.124]}>
                <group name="Object682_normal_0_178">
                  <mesh
                    name="Object_196"
                    geometry={nodes.Object_196.geometry}
                    material={materials.normal}
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            name="wire3_179"
            position={[-3.768, -84.443, -56.369]}
            rotation={[-Math.PI / 2, 0, 0.069]}
          >
            <group
              name="_180"
              position={[-83.209, -25.286, 89.846]}
              rotation={[0, 0, -0.069]}
            >
              <group name="wire3_normal_0_181">
                <mesh
                  name="Object_200"
                  geometry={nodes.Object_200.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="wire4_182"
            position={[50.921, -99.013, -52.273]}
            rotation={[-1.559, 0.072, -0.166]}
          >
            <group
              name="_183"
              position={[-129.692, -48.861, 104.416]}
              rotation={[0, 0, 0.165]}
            >
              <group name="wire4_normal_0_184">
                <mesh
                  name="Object_204"
                  geometry={nodes.Object_204.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="wire5_185"
            position={[77.672, -109.814, -59.703]}
            rotation={[-1.557, -0.049, 0.285]}
          >
            <group
              name="_186"
              position={[-165.796, 12.777, 115.217]}
              rotation={[0, 0, -0.284]}
            >
              <group name="wire5_normal_0_187">
                <mesh
                  name="Object_208"
                  geometry={nodes.Object_208.geometry}
                  material={materials.normal}
                />
              </group>
            </group>
          </group>
          <group
            name="Object706_202"
            position={[26.374, -164.473, 185.106]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="_203" position={[-111.42, 210.54, 169.876]}>
              <group name="Object706_Material_#5518_0_204">
                <mesh
                  name="Object_231"
                  geometry={nodes.Object_231.geometry}
                  material={materials.Material_5518}
                />
              </group>
            </group>
          </group>
          <group
            name="Object707_205"
            position={[26.374, -163.141, 185.106]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="_206" position={[-111.42, 210.54, 168.544]}>
              <group name="Object707_Material_#5518_0_207">
                <mesh
                  name="Object_235"
                  geometry={nodes.Object_235.geometry}
                  material={materials.Material_5518}
                />
              </group>
            </group>
          </group>
          <group
            name="Object708_208"
            position={[-121.509, 153.741, 54.209]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="_209" position={[-111.42, 210.54, 169.876]}>
              <group name="Object708_Material_#5518_0_210">
                <mesh
                  name="Object_239"
                  geometry={nodes.Object_239.geometry}
                  material={materials.Material_5518}
                />
              </group>
            </group>
          </group>
          <group
            name="Object709_211"
            position={[-121.509, 155.073, 54.209]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="_212" position={[-111.42, 210.54, 168.544]}>
              <group name="Object709_Material_#5518_0_213">
                <mesh
                  name="Object_243"
                  geometry={nodes.Object_243.geometry}
                  material={materials.Material_5518}
                />
              </group>
            </group>
          </group>
        </group>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <mesh
          name="Object_63"
          geometry={nodes.Object_63.geometry}
          material={materials.normal}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_65"
          geometry={nodes.Object_65.geometry}
          material={materials.paintmat}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_67"
          geometry={nodes.Object_67.geometry}
          material={materials.metalmat}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_69"
          geometry={nodes.Object_69.geometry}
          material={materials.Plastic_Soft}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_71"
          geometry={nodes.Object_71.geometry}
          material={materials.alpha_glass}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_73"
          geometry={nodes.Object_73.geometry}
          material={materials.glassmat}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_75"
          geometry={nodes.Object_75.geometry}
          material={materials.Material_5511}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_77"
          geometry={nodes.Object_77.geometry}
          material={materials.Material_5512}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_79"
          geometry={nodes.Object_79.geometry}
          material={materials.glass_transp}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_81"
          geometry={nodes.Object_81.geometry}
          material={materials.interiors}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_83"
          geometry={nodes.Object_83.geometry}
          material={materials.alpha}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_90"
          geometry={nodes.Object_90.geometry}
          material={materials.outline}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_211"
          geometry={nodes.Object_211.geometry}
          material={materials.Material_5516}
          position={[-1.574, 0.1, -0.471]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.019}
        />
        <mesh
          name="Object_216"
          geometry={nodes.Object_216.geometry}
          material={materials.alpha_0}
          position={[-1.487, -2.573, 3.4]}
          rotation={[-1.891, 0.86, -1.371]}
          scale={0.015}
        />
        <skinnedMesh
          name="Object_12"
          geometry={nodes.Object_12.geometry}
          material={materials.normal}
          skeleton={nodes.Object_12.skeleton}
          scale={0.019}
        />
        <skinnedMesh
          name="Object_14"
          geometry={nodes.Object_14.geometry}
          material={materials.metalmat}
          skeleton={nodes.Object_14.skeleton}
          scale={0.019}
        />
        <skinnedMesh
          name="Object_16"
          geometry={nodes.Object_16.geometry}
          material={materials.normal}
          skeleton={nodes.Object_16.skeleton}
          scale={0.019}
        />
        <skinnedMesh
          name="Object_18"
          geometry={nodes.Object_18.geometry}
          material={materials.normal}
          skeleton={nodes.Object_18.skeleton}
          scale={0.019}
        />
        <skinnedMesh
          name="Object_20"
          geometry={nodes.Object_20.geometry}
          material={materials.normal}
          skeleton={nodes.Object_20.skeleton}
          scale={0.019}
        />
        <skinnedMesh
          name="Object_22"
          geometry={nodes.Object_22.geometry}
          material={materials.normal}
          skeleton={nodes.Object_22.skeleton}
          scale={0.019}
        />
        <skinnedMesh
          name="Object_24"
          geometry={nodes.Object_24.geometry}
          material={materials.normal}
          skeleton={nodes.Object_24.skeleton}
          scale={0.019}
        />
        <skinnedMesh
          name="Object_26"
          geometry={nodes.Object_26.geometry}
          material={materials.normal}
          skeleton={nodes.Object_26.skeleton}
          scale={0.019}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/tokyo-transformed.glb");
