/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 destiny_2.glb -T -i s -m
Author: Daniel Cardona (https://sketchfab.com/DanielCardonaArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/destiny-2-character-bust-a56b08cf4d6948bdbdd1f7cd7a12d98a
Title: Destiny 2 Character Bust
*/

import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect } from "react";

export function Model(props) {
  const { nodes, materials, animations } = useGLTF(
    "/destiny_2-transformed.glb"
  );
  const { actions, names, ref } = useAnimations(animations);
  useEffect(() => {
    actions[names[0]].fadeIn(4).play();
    return () => actions[names[0]].fadeOut(0).play();
  }, [actions, names]);
  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Object_4" userData={{ name: "Object_4" }}>
          <group
            name="pCylinder1"
            position={[0, 9, -17.831]}
            scale={[31.364, 28.498, 31.364]}
            userData={{ name: "pCylinder1" }}
          >
            <mesh
              name="pCylinder1_smokeM_0"
              geometry={nodes.pCylinder1_smokeM_0.geometry}
              material={materials.smokeM}
              userData={{ name: "pCylinder1_smokeM_0" }}
            />
          </group>
          <group
            name="polySurface4"
            position={[-6.223, -3.293, -0.191]}
            userData={{ name: "polySurface4" }}
          >
            <mesh
              name="polySurface4_BustM_0"
              geometry={nodes.polySurface4_BustM_0.geometry}
              material={materials.BustM}
              userData={{ name: "polySurface4_BustM_0" }}
            />
          </group>
          <group
            name="polySurface3"
            position={[-7.017, -5.392, -0.191]}
            userData={{ name: "polySurface3" }}
          >
            <mesh
              name="polySurface3_BustM_0"
              geometry={nodes.polySurface3_BustM_0.geometry}
              material={materials.BustM}
              userData={{ name: "polySurface3_BustM_0" }}
            />
          </group>
          <group
            name="polySurface2"
            position={[-7.665, -6.398, -0.191]}
            userData={{ name: "polySurface2" }}
          >
            <mesh
              name="polySurface2_BustM_0"
              geometry={nodes.polySurface2_BustM_0.geometry}
              material={materials.BustM}
              userData={{ name: "polySurface2_BustM_0" }}
            />
          </group>
          <group
            name="polySurface1"
            position={[-6.368, -4.489, -0.191]}
            userData={{ name: "polySurface1" }}
          >
            <mesh
              name="polySurface1_BustM_0"
              geometry={nodes.polySurface1_BustM_0.geometry}
              material={materials.BustM}
              userData={{ name: "polySurface1_BustM_0" }}
            />
          </group>
        </group>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.BustM}
          skeleton={nodes.Object_7.skeleton}
          userData={{ name: "Object_7" }}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/destiny_2-transformed.glb");
