/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 robot.glb -kKmsrT
Author: Sihgames (https://sketchfab.com/sihagames)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-supersoldier-game-ready-animated-09e0bd9c9715463584cd847d9b30a140
Title: SCI-FI SuperSoldier - Game-ready [ANIMATED]
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/glb/robot-transformed.glb"
  );
  const { actions, names, ref } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]].fadeIn(0).play();
  }, []);

  useFrame(({ clock }) => {
    if (ref.current) {
      const e = clock.getElapsedTime();
      group.current.rotateX = e;
    }
  });

  return (
    <group
      scale={1.7}
      position={[0, -2.5, 0]}
      ref={group}
      {...props}
      dispose={null}
    >
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_7.skeleton}
          scale={0.017}
          userData={{ name: "Object_7" }}
        />
        <skinnedMesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials.Ch44_body1}
          skeleton={nodes.Object_8.skeleton}
          scale={0.017}
          userData={{ name: "Object_8" }}
        />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.Ch44_Body}
          skeleton={nodes.Object_9.skeleton}
          scale={0.017}
          userData={{ name: "Object_9" }}
        />
        <skinnedMesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials.Ch44_Body}
          skeleton={nodes.Object_11.skeleton}
          scale={0.017}
          userData={{ name: "Object_11" }}
        />
        <skinnedMesh
          name="Object_13"
          geometry={nodes.Object_13.geometry}
          material={materials.Ch44_Body}
          skeleton={nodes.Object_13.skeleton}
          scale={0.017}
          userData={{ name: "Object_13" }}
        />
        <skinnedMesh
          name="Object_15"
          geometry={nodes.Object_15.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_15.skeleton}
          scale={0.017}
          userData={{ name: "Object_15" }}
        />
        <skinnedMesh
          name="Object_17"
          geometry={nodes.Object_17.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_17.skeleton}
          scale={0.017}
          userData={{ name: "Object_17" }}
        />
        <skinnedMesh
          name="Object_19"
          geometry={nodes.Object_19.geometry}
          material={materials.Ch44_body1}
          skeleton={nodes.Object_19.skeleton}
          scale={0.017}
          userData={{ name: "Object_19" }}
        />
        <skinnedMesh
          name="Object_21"
          geometry={nodes.Object_21.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_21.skeleton}
          scale={0.017}
          userData={{ name: "Object_21" }}
        />
        <skinnedMesh
          name="Object_23"
          geometry={nodes.Object_23.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_23.skeleton}
          scale={0.017}
          userData={{ name: "Object_23" }}
        />
        <skinnedMesh
          name="Object_25"
          geometry={nodes.Object_25.geometry}
          material={materials.Ch44_Body}
          skeleton={nodes.Object_25.skeleton}
          scale={0.017}
          userData={{ name: "Object_25" }}
        />
        <skinnedMesh
          name="Object_27"
          geometry={nodes.Object_27.geometry}
          material={materials.Ch44_Body}
          skeleton={nodes.Object_27.skeleton}
          scale={0.017}
          userData={{ name: "Object_27" }}
        />
        <skinnedMesh
          name="Object_29"
          geometry={nodes.Object_29.geometry}
          material={materials.Ch44_Body}
          skeleton={nodes.Object_29.skeleton}
          scale={0.017}
          userData={{ name: "Object_29" }}
        />
        <skinnedMesh
          name="Object_31"
          geometry={nodes.Object_31.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_31.skeleton}
          scale={0.017}
          userData={{ name: "Object_31" }}
        />
        <skinnedMesh
          name="Object_33"
          geometry={nodes.Object_33.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_33.skeleton}
          scale={0.017}
          userData={{ name: "Object_33" }}
        />
        <skinnedMesh
          name="Object_35"
          geometry={nodes.Object_35.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_35.skeleton}
          scale={0.017}
          userData={{ name: "Object_35" }}
        />
        <skinnedMesh
          name="Object_37"
          geometry={nodes.Object_37.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_37.skeleton}
          scale={0.017}
          userData={{ name: "Object_37" }}
        />
        <skinnedMesh
          name="Object_39"
          geometry={nodes.Object_39.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_39.skeleton}
          scale={0.017}
          userData={{ name: "Object_39" }}
        />
        <skinnedMesh
          name="Object_41"
          geometry={nodes.Object_41.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_41.skeleton}
          scale={0.017}
          userData={{ name: "Object_41" }}
        />
        <skinnedMesh
          name="Object_43"
          geometry={nodes.Object_43.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_43.skeleton}
          scale={0.017}
          userData={{ name: "Object_43" }}
        />
        <skinnedMesh
          name="Object_45"
          geometry={nodes.Object_45.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_45.skeleton}
          scale={0.017}
          userData={{ name: "Object_45" }}
        />
        <skinnedMesh
          name="Object_47"
          geometry={nodes.Object_47.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_47.skeleton}
          scale={0.017}
          userData={{ name: "Object_47" }}
        />
        <skinnedMesh
          name="Object_49"
          geometry={nodes.Object_49.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_49.skeleton}
          scale={0.017}
          userData={{ name: "Object_49" }}
        />
        <skinnedMesh
          name="Object_51"
          geometry={nodes.Object_51.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_51.skeleton}
          scale={0.017}
          userData={{ name: "Object_51" }}
        />
        <skinnedMesh
          name="Object_53"
          geometry={nodes.Object_53.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_53.skeleton}
          scale={0.017}
          userData={{ name: "Object_53" }}
        />
        <skinnedMesh
          name="Object_55"
          geometry={nodes.Object_55.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_55.skeleton}
          scale={0.017}
          userData={{ name: "Object_55" }}
        />
        <skinnedMesh
          name="Object_57"
          geometry={nodes.Object_57.geometry}
          material={materials.Ch44_body1}
          skeleton={nodes.Object_57.skeleton}
          scale={0.017}
          userData={{ name: "Object_57" }}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/glb/robot-transformed.glb");
